dataset:
  name: "system-path-test"
  version: "1.0"
  config:
    expected_output_field: expected_output

evaluators:
  - id: "deep_nested_eval"
    name: "deep_nested_evaluator"
    data_mapping: {}
  - id: "utils_eval"
    name: "utility_evaluator"
    data_mapping: {}

executable:
  type: "module"
  path: "main_processor"
  processor: "run"
  python_path:
    - "nested/deep/evaluators"
    - "utils/helpers"
    - "shared/common"
  config: {}

local_mode: true
output_path: "results/"