dataset:
  name: "nested-test"
  version: "1.0"
  config:
    expected_output_field: expected_output

evaluators:
  - id: "basic_length_eval"
    name: "basic_length"
    data_mapping: {}
  - id: "basic_complete_eval"
    name: "basic_completeness"
    data_mapping: {}
  - id: "advanced_quality_eval"
    name: "advanced_quality"
    data_mapping: {}
  - id: "advanced_coherence_eval"
    name: "advanced_coherence"
    data_mapping: {}

executable:
  type: "module"
  path: "nested_evaluator_loader"
  processor: "run"
  config: {}

local_mode: true
output_path: "results/"