dataset:
  name: "hello-world"
  version: "1.0"
  config:
    expected_output_field: expected_output

evaluators:
  - id: "response_length_eval"
    name: "response_length"
    data_mapping: {}

executable:
  type: "module"
  path: "simple_echo_module"
  processor: "run"
  config: {}

local_mode: true
output_path: "results/"